owner: uracilo # GitHub username
repo: servicelevels # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - Uracilo
#status-website: # Status website (optional)
#  cname: upptime.js.org # Custom domain CNAME
#  name: Upptime # Status website title
status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Your Status Website
